### ISSUE TITLE
Steam Screenshots while playing certain MIDI files

### ISSUE THREAD

**Issue by Kisutora** [ianespana/ShawzinBot#11] opened 2019-09-07 08:52 UTC
Sometimes Steam will take a screenshot while playing certain MIDI files.
I have set my Steam screenshot shortcut to none but it still takes pictures.

Two MIDI that seem to reproduce this issue, pick your poison:
https://mega.nz/#!WqhUAAZB!zyrnHQIJKDI9aXHFdKgl3uP3V6c8vhX_zuyHjyb6718
![Steam_6Gp4JH3emE](https://user-images.githubusercontent.com/22685232/64472363-c778de00-d165-11e9-9182-d720b323160a.png)

**Comment by Pawel-Dymek** [comment] 2019-09-07 21:11
same here

**Comment by ianespana** [comment] 2019-09-10 02:18
Will look into this... Weird

**Comment by noobchief** [comment] 2019-09-10 13:14
It's default «shift+tab» screenshot hotkey I guess.

**Comment by ianespana** [comment] 2019-09-11 23:07
Are you by any chance pressing something on your keyboard while the bot is playing? I couldn't reproduce this myself

**Comment by Kisutora** [comment] 2019-09-13 15:23
Not pressing any buttons, but it seems to be pretty inconsistent. Sometimes you get screenshots and sometimes you don't.

**Comment by ianespana** [comment] 2019-09-21 16:24
Haven't been able to reproduce this. Closing the issue until more information is given

**Closed as completed by ianespana** 2019-09-21 16:24 UTC
Labels: bug, question

**Comment by Nicolas-GE** [comment] 2021-04-20 12:42
i also have this issue, this seems related to the midi played, i have linked one that causes the issue in #37
